---
apiVersion: platform.psk.io/v1alpha1
kind: S3Bucket
metadata:
  name: loki
  namespace: {{ $.Values.namespace }}
spec:
  serviceAccountName: loki
  access: readwritedelete
  versioning: false
  expireAfterDays: 0

---
apiVersion: platform.psk.io/v1alpha1
kind: S3Bucket
metadata:
  name: mimir
  namespace: {{ $.Values.namespace }}
spec:
  serviceAccountName: mimir
  access: readwritedelete
  versioning: false
  expireAfterDays: 0

---
apiVersion: platform.psk.io/v1alpha1
kind: S3Bucket
metadata:
  name: tempo
  namespace: {{ $.Values.namespace }}
spec:
  serviceAccountName: tempo
  access: readwritedelete
  versioning: false
  expireAfterDays: 0