apiVersion: v2
name: mimir
description: Mimir on-cluster metrics collection
type: application
version: 0.1.0
maintainers:
  - name: Thoughtworks, Inc.
    url: https://github.com/twplatformlabs
appVersion: "3.1.0"