version: 2.1

orbs:
  kube: twdps/kube-ops@dev:alpha
  op: twdps/onepassword@3.0.0
  do: twdps/pipeline-events@5.4.0

globals:
  - &context platform
  - &executor-image ghcr.io/twplatformlabs/circleci-eks-ops:alpine-2026.06
  - &config-repo twplatformlabs/psk-aws-control-plane-configuration

on-push-main: &on-push-main
  branches:
    only: /main/
  tags:
    ignore: /.*/

on-tag-main: &on-tag-main
  branches:
    ignore: /.*/
  tags:
    only: /.*/

commands:

  set-environment:
    description: generate environment credentials and configuration from templates
    parameters:
      cluster:
        description: access cluster for testing
        type: string
    steps:
      - op/env:
          env-file: op.<< parameters.cluster >>.env
      - kube/op-kubeconfig:
          op-value: platform/<< parameters.cluster>>/kubeconfig-base64
      - do/bash-functions

jobs:

  update observability deployment configuration:
    docker:
      - image: *executor-image
    parameters:
      cluster-role:
        description: cluster role to be updated
        type: string
    steps:
      - checkout
      - op/env
      - do/bash-functions
      - run:
          name: generate application resource for observability dependencies (syncWave 2)
          command: bash scripts/generate_obs_dependencies_application.sh << parameters.cluster-role >>
      - kube/write-to-github:
          source: deploy-files/obs-dependencies/*
          destination: "roles/<<parameters.cluster-role>>/obs-dependencies"
          repository-url: *config-repo
      - run:
          name: generate application resource for storage targets (syncWave 3)
          command: |
            bash scripts/generate_loki_application.sh << parameters.cluster-role >>
            bash scripts/generate_mimir_application.sh << parameters.cluster-role >>
            bash scripts/generate_tempo_application.sh << parameters.cluster-role >>
      - kube/write-to-github:
          source: deploy-files/loki/*
          destination: "roles/<<parameters.cluster-role>>/loki"
          repository-url: *config-repo
      - kube/write-to-github:
          source: deploy-files/mimir/*
          destination: "roles/<<parameters.cluster-role>>/mimir"
          repository-url: *config-repo
      - kube/write-to-github:
          source: deploy-files/tempo/*
          destination: "roles/<<parameters.cluster-role>>/tempo"
          repository-url: *config-repo
      - run:
          name: generate application resource for collectors (syncWave 4)
          command: |
            bash scripts/generate_otel_daemonset_application.sh << parameters.cluster-role >>
            bash scripts/generate_otel_singleton_application.sh << parameters.cluster-role >>
            bash scripts/generate_grafana_application.sh << parameters.cluster-role >>
      - kube/write-to-github:
          source: deploy-files/otel-daemonset/*
          destination: "roles/<<parameters.cluster-role>>/otel-daemonset"
          repository-url: *config-repo
      - kube/write-to-github:
          source: deploy-files/otel-singleton/*
          destination: "roles/<<parameters.cluster-role>>/otel-singleton"
          repository-url: *config-repo
      - kube/write-to-github:
          source: deploy-files/grafana/*
          destination: "roles/<<parameters.cluster-role>>/grafana"
          repository-url: *config-repo

  functional-tests:
    docker:
      - image: *executor-image
    parameters:
      cluster:
        description: cluster to test
        type: string
      cluster-role:
        description: cluster role to be updated
        type: string
    steps:
      - checkout
      - set-environment:
          cluster: << parameters.cluster >>
      - run:
          name: run integration test of observability and customizations
          command: bash scripts/integration_tests.sh << parameters.cluster >> << parameters.cluster-role >>

workflows:

  deploy sandbox role configuration:
    when:
      not:
        equal: [ scheduled_pipeline, << pipeline.trigger_source >> ]
    jobs:
      - update observability deployment configuration:
          name: update sandbox configuration
          context: *context
          cluster-role: sandbox
          filters: *on-push-main

      - functional-tests:
          name: test sandbox cluster
          context: *context
          cluster: sbx-i01-aws-us-east-1
          cluster-role: sandbox
          requires:
            - update sandbox configuration
          filters: *on-push-main
  
  deploy production role configuration:
    jobs:
      - update observability deployment configuration:
          name: update production configuration
          context: *context
          cluster-role: production
          filters: *on-tag-main

      - functional-tests:
          name: test production cluster
          context: *context
          cluster: prod-i01-aws-us-east-2
          cluster-role: production
          requires:
            - update production configuration
          filters: *on-tag-main

  #     - do/gh-release:
  #         name: generate release notes
  #         context: *context
  #         notes-from-file: release.md
  #         include-commit-msg: true
  #         before-release:
  #           - op/env:
  #               env-file: op.prod-i01-aws-us-east-2.env
  #         requires:
  #           - test production cluster
  #         filters: *on-tag-main

  #     - do/schedule-pipeline:
  #         name: schedule nightly functional tests
  #         context: *context
  #         scheduled-pipeline-name: nightly observability operator functional test
  #         scheduled-pipeline-description: |
  #           Automatically triggers nightly run of functional-test job
  #         hours-of-day: "[1]"
  #         days-of-week: "[\"SUN\"]"
  #         before-schedule:
  #           - op/env:
  #               env-file: op.prod-i01-aws-us-east-2.env
  #         filters: *on-tag-main

  # run nightly integration test:
  #   when:
  #     equal: [ scheduled_pipeline, << pipeline.trigger_source >> ]
  #   jobs:
  #     - functional-tests:
  #         name: nightly sbx-i01-aws-us-east-1 functional test
  #         cluster: sbx-i01-aws-us-east-1
  #         cluster-role: sandbox
  #         context: *context
  #     - functional-tests:
  #         name: nightly prod-i01-aws-us-east-2 functional test
  #         cluster: prod-i01-aws-us-east-2
  #         cluster-role: production
  #         context: *context