apiVersion: v1
kind: Service
metadata:
  name: {{ include "tempo.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "tempo.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "tempo.selectorLabels" . | nindent 4 }}
  ports:
    - name: http          # query API / Grafana datasource
      port: 3200
      targetPort: http
    - name: grpc
      port: 9095
      targetPort: grpc
    - name: otlp-grpc     # senders push traces here
      port: 4317
      targetPort: otlp-grpc
    - name: otlp-http
      port: 4318
      targetPort: otlp-http

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "tempo.fullname" . }}-gossip-ring
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "tempo.labels" . | nindent 4 }}
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    {{- include "tempo.selectorLabels" . | nindent 4 }}
  ports:
    - name: gossip
      port: 7946
      targetPort: gossip