apiVersion: v1
kind: Service
metadata:
  name: {{ include "mimir.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mimir.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "mimir.selectorLabels" . | nindent 4 }}
  ports:
    - name: http          # remote_write in, PromQL out, Alertmanager API
      port: 8080
      targetPort: http
    - name: grpc
      port: 9095
      targetPort: grpc

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "mimir.fullname" . }}-gossip-ring
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mimir.labels" . | nindent 4 }}
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    {{- include "mimir.selectorLabels" . | nindent 4 }}
  ports:
    - name: gossip
      port: 7946
      targetPort: gossip